extern fn printf(fmt: str, ...) i32
extern fn getchar() i32

def print_error_box() -> void:
    printf("\n")
    printf("BoxDrawing Error:\n")
    printf("\n")
    printf("================================\n")
    printf("    CRITICAL ERROR - System32  \n")
    printf("================================\n")
    printf("\n")
    printf("Error Code: 0x80004005\n")
    printf("Module: kernel32.dll\n")
    printf("Description: System32 File Corrupted\n")
    printf("\n")
    printf("Your system may be damaged.\n")
    printf("\n")
    printf("================================\n")
    printf("Generated by: CBlerr v4.0\n")
    printf("================================\n")
    printf("\n")

def print_recovery_menu() -> void:
    printf("\n")
    printf("================================\n")
    printf("  System Recovery Options\n")
    printf("================================\n")
    printf("\n")
    printf("[1] Attempt System Recovery\n")
    printf("[2] Scan and Repair System Files\n")
    printf("[3] Shutdown\n")
    printf("\n")
    printf("Enter option (1-3): ")

def print_recovery_success() -> void:
    printf("\n")
    printf("================================\n")
    printf("  Recovery Successful\n")
    printf("================================\n")
    printf("\n")
    printf("Scanning system files...\n")
    printf("[████████████████████] 100%\n")
    printf("\n")
    printf("Check complete! System is healthy.\n")
    printf("\n")
    printf("================================\n")
    printf("\n")

def print_final_message() -> void:
    printf("\n")
    printf("================================\n")
    printf("  CBlerr Demo Complete\n")
    printf("================================\n")
    printf("\n")
    printf("This was a demonstration of fake\n")
    printf("system error UI using CBlerr.\n")
    printf("\n")
    printf("The CBlerr compiler successfully\n")
    printf("generated executable code.\n")
    printf("\n")
    printf("================================\n")
    printf("\n")

def main() -> i32:
    printf("=== CBlerr Fake Error UI Demo ===\n")
    printf("Press ENTER to show error message...\n")
    key1: i32 = getchar()
    
    print_error_box()
    
    printf("Press ENTER to show recovery menu...\n")
    key2: i32 = getchar()
    
    print_recovery_menu()
    key3: i32 = getchar()
    
    print_recovery_success()
    
    printf("Press ENTER to show final message...\n")
    key4: i32 = getchar()
    
    print_final_message()
    
    printf("Press any key to exit...\n")
    key5: i32 = getchar()
    
    return 0
